default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: book_review_development

test:
  <<: *default
  url: <%= ENV['DATABASE_TEST_URL'] %>
  host: 127.0.0.1
  database: book_review_test
  username: <%= ENV['MYSQL_ROOT_USER'] %>
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
