version: 2.1

commands:
  build_and_exec_rspec:
    steps:
      - run:
          name: Prepare DB for RSpec
          command: |
            cd backend && bundle ex rails db:create RAILS_ENV=test
            cd backend && bundle ex rails ridgepole:apply RAILS_ENV=test
      - run:
          name: Run RSpec
          command: cd backend && bundle ex rspec

  install_yarn:
    steps:
      - restore_cache:
          keys:
            - v1-npm-{{ arch }}-{{ checksum "frontend/yarn.lock" }}
            - v1-npm-
      - run: cd frontend && yarn install --frozen-lockfile
      - save_cache:
          paths:
            - frontend/node_modules
          key: v1-npm-{{ arch }}-{{ checksum "frontend/yarn.lock" }}

  install_gems:
    steps:
      - run:
          name: Backup backend/Gemfile.lock for cache key
          command: cp backend/Gemfile.lock backend/Gemfile.lock.bak
      - restore_cache:
          keys:
            - v1-gems-{{ arch }}-{{ checksum "backend/Gemfile.lock.bak" }}
            - v1-gems-
      - run:
          name: Install Bundler
          command: gem install bundler -v 1.15.0
      - run: cd backend && bundle config set path 'vendor/bundle'
      - run: cd backend && bundle install -j4
      - save_cache:
          paths:
            - backend/vendor/bundle
          key: v1-gems-{{ arch }}-{{ checksum "backend/Gemfile.lock.bak" }}

jobs:
  frontend_lint:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout
      - install_yarn
      - run: cd frontend && yarn lint
      - run: cd frontend && yarn tsc --noEmit

  backend_lint:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - checkout
      - install_gems
      - run: cd backend && bundle exec rubocop

  backend_repec:
    docker:
      - image: cimg/ruby:3.2.2
      - image: cimg/mysql:5.7
    steps:
      - checkout
      - install_gems
      - build_and_exec_rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - frontend_lint
      - backend_lint
      - backend_repec
