name: frontend

on:
  pull_request:
    branches:
      - main

env:
  DOCKERFILE_PATH: frontend/Dockerfile
  IMAGE_TAG: frontend_image_tag
  DOCKERIZE_VERSION: v0.6.1

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.x"

      - name: Install dependencies
        run: yarn

      - name: Yarn Install
        run: yarn install
        working-directory: ./frontend

      - name: Run Lint
        run: yarn lint
        working-directory: ./frontend

      - name: Run Prettier
        run: yarn prettier
        working-directory: ./frontend

      - name: Run Tsc
        run: yarn tsc
        working-directory: ./frontend
